---

---

```{r setup}

knitr::opts_chunk$set(fig.align = "center", fig.width = 8, fig.asp = 0.618)

library(tidyverse)
#devtools::install_github("jtcies/jtcr")
library(jtcr)
library(irlba)
library(glmnet)
library(randomForest)
library(caret)

theme_set(theme_jtc())

rmse <- function(pred, actual) {

    resid <- pred - actual
    sqrt(mean(resid^2))
}

# download from my github for reproducibility
batting <- read_csv("https://raw.githubusercontent.com/jtcies/phillies-task/master/batting.csv") %>%
   janitor::clean_names()

# bring in two additional data sets, both from fangraphs
# batted ball data from mar/apr 2018

batted_ball <- read_csv("https://raw.githubusercontent.com/jtcies/phillies-task/master/batted-ball-2018.csv") %>%
    janitor::clean_names() %>%
    select(-name, -team, -babip) %>% 
    mutate_if(is.character, readr::parse_number) %>% 
    mutate_at(vars(ends_with("percent")), function(x) x / 100)

# and batting data from full 2017 season

batting_2017 <- read_csv("https://raw.githubusercontent.com/jtcies/phillies-task/master/batting-2017.csv") %>%
    janitor::clean_names() %>%
    select(-name, -team, -ubr, -w_gdp, -w_rc_2) %>% 
    mutate_if(is.character, readr::parse_number) %>% 
    mutate_at(vars(ends_with("percent")), function(x) x / 100)
 
colnames(batting_2017) <- paste0(colnames(batting_2017), "_2017")

full_batting <- batting %>%
    left_join(batted_ball, by = "playerid") %>%
    left_join(batting_2017, by = c("playerid" = "playerid_2017"))

set.seed(2019)

train <- full_batting %>%
    sample_frac(0.8)

test <- full_batting %>%
    filter(!playerid %in% train$playerid)

```

```{r missing}

#sum(!complete.cases(train))
# not many missing so i will just take the mean

train_means <- lapply(train[, 4:ncol(train)], function(x) mean(x, na.rm = TRUE)) 

impute_missing <- function(df) {

    ret <- df[, 4:ncol(df)]

     for(i in 1:ncol(ret)) {
        for (j in 1:nrow(ret)) {
           if (is.na(ret[j, i])) {
               ret[j, i] <- train_means[[i]]
            }
        }

    }

    bind_cols(df[, 1:3], ret)
}

train_impute <- impute_missing(train)

```

## EDA

```{r eda}

train_impute %>%
    ggplot(aes(full_season_avg)) +
        geom_histogram(binwidth = 0.01) +
        labs(title = "Distribution of final average")
```

```{r}

# normally distributed

as_tibble(cor(train_impute[, 4:ncol(train_impute)])) %>%
    mutate(var1 = colnames(train[, 4:ncol(train_impute)])) %>%
    gather(var2, cor, -var1) %>%
    ggplot(aes(var1, var2, fill = cor)) +
        geom_tile() +
        scale_fill_gradient2() +
        theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
        labs(title = "Correlation Matrix")

```
```{r}

train %>%
    ggplot(aes(mar_apr_avg, full_season_avg)) +
        geom_point() +
        geom_smooth(method = "lm") +
        geom_abline(color = "red") +
        geom_hline(yintercept = mean(train$mar_apr_avg), linetype = 3) +
        geom_vline(xintercept = mean(train$full_season_avg), linetype = 3)

# regression to the mean

```

## PCA

```{r pca}

# https://juliasilge.com/blog/stack-overflow-pca/

avg_pca <- prcomp_irlba(
    train_impute[, 4:ncol(train_impute)],
    n = 56, 
    scale. = TRUE
)

pca_tidy <- as_tibble(avg_pca$rotation) %>%
    mutate(var = colnames(train_impute[, 4:ncol(train_impute)])) %>%
    gather(pc, contribution, -var)

tibble(variance = avg_pca$sdev^2, pc = 1:56) %>%
    mutate(
        prop_var = variance / sum(variance), 
        cumulative_variance = cumsum(prop_var)
    ) %>%
    ggplot(aes(pc, cumulative_variance)) +
        geom_line() +
        geom_point() +
        labs(title = "Proportion of variance explained by each PC")

# it looks like most of the variance is explained by the first 40 pcs

```

## model

```{r modelsetup}

# https://topepo.github.io/caret/model-training-and-tuning.html#basic-parameter-tuning
train_scaled <- train_impute %>%
    select(4:ncol(train_impute)) %>%
    mutate_all(function(x) scale(x)[,1])

train_model <- bind_cols(train_scaled, tbl_df(avg_pca$x[, 1:40]))


fit_ctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 10)

```

```{r rf}

rf_tune <- expand.grid(.mtry = 10:90)

rf_fit <- caret::train(
    full_season_avg ~ ., 
    method = "rf",
    data = train_model,
    trControl = fit_ctrl
)

```

